# This is a basic workflow for github actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
<<<<<<< HEAD
  run_awesome_lint:
=======
  run_tests:
>>>>>>> bdd7156... add awesome lint
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
<<<<<<< HEAD
        with:
          ## fetch depth 0 (aka fetch all) is needed to check repo age
          fetch-depth: 0
      
      - name: Run awesome-lint
        run: npx awesome-lint
=======

      - name: Install dependencies
        run: npm install --global awesome-lint
      
      - name: Run awesome-lint
        run: awesome-lint
>>>>>>> bdd7156... add awesome lint
